In [83]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [84]:
df=pd.read_csv('train.txt',sep=';',header=None,names=['text','emotion'])

In [85]:
df.head()

,text,emotion
0,i didnt feel humiliated,sadness
1,i can go from feeling so hopeless to so damned...,sadness
2,im grabbing a minute to post i feel greedy wrong,anger
3,i am ever feeling nostalgic about the fireplac...,love
4,i am feeling grouchy,anger


In [86]:
df.isnull().sum()

,0
text,0
emotion,0


In [87]:
unique_emotion=df['emotion'].unique()

In [88]:
emotion_number={}
i=0
for emo in unique_emotion:
    emotion_number[emo]=i
    i+=1
df['emotion']=df['emotion'].map(emotion_number)


In [89]:
df

,text,emotion
0,i didnt feel humiliated,0
1,i can go from feeling so hopeless to so damned...,0
2,im grabbing a minute to post i feel greedy wrong,1
3,i am ever feeling nostalgic about the fireplac...,2
4,i am feeling grouchy,1
...,...,...
15995,i just had a very brief time in the beanbag an...,0
15996,i am now turning and i feel pathetic that i am...,0
15997,i feel strong and good overall,5
15998,i feel like this was such a rude comment and i...,1


In [90]:
df['text']=df['text'].apply(lambda x: x.lower())

In [91]:
df

,text,emotion
0,i didnt feel humiliated,0
1,i can go from feeling so hopeless to so damned...,0
2,im grabbing a minute to post i feel greedy wrong,1
3,i am ever feeling nostalgic about the fireplac...,2
4,i am feeling grouchy,1
...,...,...
15995,i just had a very brief time in the beanbag an...,0
15996,i am now turning and i feel pathetic that i am...,0
15997,i feel strong and good overall,5
15998,i feel like this was such a rude comment and i...,1


In [92]:
import string
def remove_pun(txt):
  return txt.translate(str.maketrans('','',string.punctuation))


In [93]:
df['text']=df['text'].apply(remove_pun)

In [94]:
df["text"] = df["text"].str.replace(r"\d+", "", regex=True)

In [95]:
df["text"] = df["text"].str.replace(
    r"https?://\S+|www\.\S+",
    "",
    regex=True
)

In [96]:
df

,text,emotion
0,i didnt feel humiliated,0
1,i can go from feeling so hopeless to so damned...,0
2,im grabbing a minute to post i feel greedy wrong,1
3,i am ever feeling nostalgic about the fireplac...,2
4,i am feeling grouchy,1
...,...,...
15995,i just had a very brief time in the beanbag an...,0
15996,i am now turning and i feel pathetic that i am...,0
15997,i feel strong and good overall,5
15998,i feel like this was such a rude comment and i...,1


In [97]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [98]:
nltk.download('punkt')
nltk.download("punkt_tab")
nltk.download('stopwords')
df

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


,text,emotion
0,i didnt feel humiliated,0
1,i can go from feeling so hopeless to so damned...,0
2,im grabbing a minute to post i feel greedy wrong,1
3,i am ever feeling nostalgic about the fireplac...,2
4,i am feeling grouchy,1
...,...,...
15995,i just had a very brief time in the beanbag an...,0
15996,i am now turning and i feel pathetic that i am...,0
15997,i feel strong and good overall,5
15998,i feel like this was such a rude comment and i...,1


In [99]:
stopw_ords = set(stopwords.words("english"))

In [100]:
df

,text,emotion
0,i didnt feel humiliated,0
1,i can go from feeling so hopeless to so damned...,0
2,im grabbing a minute to post i feel greedy wrong,1
3,i am ever feeling nostalgic about the fireplac...,2
4,i am feeling grouchy,1
...,...,...
15995,i just had a very brief time in the beanbag an...,0
15996,i am now turning and i feel pathetic that i am...,0
15997,i feel strong and good overall,5
15998,i feel like this was such a rude comment and i...,1


In [101]:
df.loc[0]['text']

'i didnt feel humiliated'

In [102]:
#function to remove stopwords
def remove(txt):
    words = word_tokenize(txt)
    cleaned = []

    for word in words:
        if word not in stopw_ords:
            cleaned.append(word)

    return " ".join(cleaned)

In [103]:
df['text']=df['text'].apply(remove)

In [104]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [105]:
df

,text,emotion
0,didnt feel humiliated,0
1,go feeling hopeless damned hopeful around some...,0
2,im grabbing minute post feel greedy wrong,1
3,ever feeling nostalgic fireplace know still pr...,2
4,feeling grouchy,1
...,...,...
15995,brief time beanbag said anna feel like beaten,0
15996,turning feel pathetic still waiting tables sub...,0
15997,feel strong good overall,5
15998,feel like rude comment im glad,1


In [106]:
#bag of words
from sklearn.feature_extraction.text import CountVectorizer
doc=[
    "i love pizza",
    "i hate pizza",
    "i love burger",
    "i hate burger"
]
v=CountVectorizer()
x=v.fit_transform(doc)
print(v.get_feature_names_out())
print(x.toarray())

['burger' 'hate' 'love' 'pizza']
[[0 0 1 1]
 [0 1 0 1]
 [1 0 1 0]
 [1 1 0 0]]


In [107]:
df

,text,emotion
0,didnt feel humiliated,0
1,go feeling hopeless damned hopeful around some...,0
2,im grabbing minute post feel greedy wrong,1
3,ever feeling nostalgic fireplace know still pr...,2
4,feeling grouchy,1
...,...,...
15995,brief time beanbag said anna feel like beaten,0
15996,turning feel pathetic still waiting tables sub...,0
15997,feel strong good overall,5
15998,feel like rude comment im glad,1


In [108]:
#bag of words
from sklearn.feature_extraction.text import TfidfVectorizer
doc=[
    "i love pizza",
    "i hate pizza",
    "i love burger",
    "i hate burger"
]
v=TfidfVectorizer()
x=v.fit_transform(doc)
print(v.get_feature_names_out())
print(x.toarray())

['burger' 'hate' 'love' 'pizza']
[[0.         0.         0.70710678 0.70710678]
 [0.         0.70710678 0.         0.70710678]
 [0.70710678 0.         0.70710678 0.        ]
 [0.70710678 0.70710678 0.         0.        ]]


In [109]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df['text'],df['emotion'],test_size=0.2,random_state=42)

In [110]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [111]:
bow=CountVectorizer()
x_train_bow=bow.fit_transform(x_train)
x_test_bow=bow.transform(x_test)

In [112]:
tf=TfidfVectorizer()
x_train_tf=tf.fit_transform(x_train)
x_test_tf=tf.transform(x_test)

In [34]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [35]:
nb=MultinomialNB()
nb.fit(x_train_bow,y_train)
y_pred=nb.predict(x_test_bow)
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test, y_pred))

0.7678125
              precision    recall  f1-score   support

           0       0.75      0.95      0.84       946
           1       0.89      0.63      0.74       427
           2       0.93      0.26      0.41       296
           3       1.00      0.05      0.10       113
           4       0.85      0.57      0.68       397
           5       0.73      0.96      0.83      1021

    accuracy                           0.77      3200
   macro avg       0.86      0.57      0.60      3200
weighted avg       0.80      0.77      0.74      3200



In [36]:
tf_nb=MultinomialNB()
tf_nb.fit(x_train_tf,y_train)
y_pred=tf_nb.predict(x_test_tf)
print(accuracy_score(y_test,y_pred))

0.6609375


In [37]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train_bow,y_train)
y_pred=lr.predict(x_test_bow)
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test, y_pred))

0.88875
              precision    recall  f1-score   support

           0       0.93      0.93      0.93       946
           1       0.89      0.85      0.87       427
           2       0.84      0.76      0.80       296
           3       0.86      0.72      0.78       113
           4       0.86      0.84      0.85       397
           5       0.88      0.94      0.91      1021

    accuracy                           0.89      3200
   macro avg       0.88      0.84      0.86      3200
weighted avg       0.89      0.89      0.89      3200



In [38]:
lr.fit(x_train_tf,y_train)
y_pred=lr.predict(x_test_tf)
print(accuracy_score(y_test,y_pred))

0.8615625


In [39]:
from sklearn.svm import SVC
svm=SVC()
svm.fit(x_train_bow,y_train)
y_pred=svm.predict(x_test_bow)
print(accuracy_score(y_test,y_pred))


0.8225


In [40]:
svm.fit(x_train_tf,y_train)
y_pred=svm.predict(x_test_tf)
print(accuracy_score(y_test,y_pred))

0.8515625


In [113]:
from sklearn.linear_model import SGDClassifier
sgd=SGDClassifier()
sgd.fit(x_train_bow,y_train)
y_pred=sgd.predict(x_test_bow)
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test, y_pred))

0.8946875
              precision    recall  f1-score   support

           0       0.93      0.93      0.93       946
           1       0.89      0.89      0.89       427
           2       0.85      0.76      0.80       296
           3       0.85      0.73      0.78       113
           4       0.85      0.87      0.86       397
           5       0.90      0.93      0.92      1021

    accuracy                           0.89      3200
   macro avg       0.88      0.85      0.86      3200
weighted avg       0.89      0.89      0.89      3200



In [114]:
sgd.fit(x_train_tf,y_train)
y_pred=sgd.predict(x_test_tf)
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test, y_pred))


0.89125
              precision    recall  f1-score   support

           0       0.92      0.93      0.93       946
           1       0.89      0.89      0.89       427
           2       0.84      0.72      0.78       296
           3       0.86      0.70      0.77       113
           4       0.87      0.85      0.86       397
           5       0.89      0.94      0.91      1021

    accuracy                           0.89      3200
   macro avg       0.88      0.84      0.86      3200
weighted avg       0.89      0.89      0.89      3200



In [122]:
text = ["I am furious that they lied to me."]

# Convert text to TF-IDF
text_tf = tf.transform(text)

# Predict
prediction = sgd.predict(text_tf)

print("Predicted Emotion:", prediction[0])

Predicted Emotion: 1


In [129]:
pd.shape

(16000, 2)